const menu=document.querySelector('.menu');const nav=document.querySelector('.navlinks');if(menu)menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const form=document.querySelector('#partner-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();form.querySelector('.success').style.display='block';form.reset()});
const slides=document.querySelector('.slides');if(slides){let current=0;const total=slides.children.length;const show=n=>{current=(n+total)%total;slides.style.transform=`translateX(-${current*100}%)`};document.querySelector('[data-next]').addEventListener('click',()=>show(current+1));document.querySelector('[data-prev]').addEventListener('click',()=>show(current-1));setInterval(()=>show(current+1),6500)}
const uploader=document.querySelector('#gallery-upload');if(uploader)uploader.addEventListener('change',()=>{const preview=document.querySelector('.upload-preview');preview.innerHTML='';[...uploader.files].slice(0,6).forEach(file=>{const url=URL.createObjectURL(file);const el=document.createElement(file.type.startsWith('video/')?'video':'img');el.src=url;if(el.tagName==='VIDEO'){el.controls=true;el.muted=true}el.alt=file.name;preview.appendChild(el)})});
document.querySelectorAll('.navlinks').forEach(n=>{if(!n.querySelector('a[href="gallery.html"]')){const partner=n.querySelector('a[href="partner.html"]');const link=document.createElement('a');link.href='gallery.html';link.textContent='Gallery';n.insertBefore(link,partner)}const info=n.querySelector('a[href="info.html"]');if(info)info.textContent='Company';const team=n.querySelector('a[href="team.html"]');if(team)team.textContent='Team'});
if(location.pathname.endsWith('ecosystem.html')){const engines=document.querySelector('.engines');if(engines)engines.insertAdjacentHTML('afterend','<div class="proof-grid" style="margin-top:45px"><div class="proof"><strong>160</strong><span>professionals in the Rembeka network</span></div><div class="proof"><strong>2,000+</strong><span>orders completed over four years</span></div><div class="proof"><strong>2027</strong><span>IVA retail and distribution launch</span></div><div class="proof"><strong>2026</strong><span>Adorn launched in Kenya</span></div></div>')}
if(location.pathname.endsWith('partner.html')){const main=document.querySelector('main');if(main)main.insertAdjacentHTML('beforeend','<section class="section blue"><div class="shell"><div class="section-head"><div><span class="eyebrow">Partner ecosystem</span></div><div><h2>Better businesses are built together.</h2><p>Co-creation, co-investment and strategic partnerships turn opportunity into momentum.</p></div></div></div><div class="partner-rail"><div class="rail-track"><span class="rail-item">Afrinext Ventures Kenya Limited</span><span class="rail-item">Kami Consult</span><span class="rail-item">Adorn Africa</span><span class="rail-item">Rembeka Online</span><span class="rail-item">Afrinext Ventures Kenya Limited</span><span class="rail-item">Kami Consult</span><span class="rail-item">Adorn Africa</span><span class="rail-item">Rembeka Online</span></div></div></section>')}
document.title=document.title.replaceAll('G-AFRICA','Gi Africa');const renameBrand=node=>{node.childNodes.forEach(child=>{if(child.nodeType===3)child.nodeValue=child.nodeValue.replaceAll('G-AFRICA','Gi Africa');else renameBrand(child)})};renameBrand(document.body);
